name: mwb_connect_app
description: MWBConnect
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
  flutter_driver:
    sdk: flutter
  integration_test: ^1.0.1        
  flutter_localizations:
    sdk: flutter

  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  cloud_firestore_mocks: ^0.7.0
  firebase_storage: ^8.0.0
  flutuate_mixpanel: ^1.1.1
  firebase_analytics: ^5.0.2
  provider: ^4.0.4
  path_provider: ^2.0.0
  get_it: ^6.0.0
  easy_localization: ^2.3.3+1
  flutter_segment: ^2.1.1
  flutter_phoenix: ^0.1.0
  devicelocale: ^0.4.0
  cupertino_icons: ^0.1.2
  google_fonts: ^2.0.0
  flutter_local_notifications: ^4.0.1+2
  flutter_widget_from_html_core: ^0.4.2
  quiver: ^2.1.3
  smooth_page_indicator: ^0.1.5
  scroll_to_index: ^1.0.6
  flutter_spinkit: ^4.1.2
  keyboard_visibility: ^0.5.6
  draggable_scrollbar: ^0.0.4
  package_info: ^0.4.1
  rxdart: ^0.23.1
  enum_to_string: ^1.0.9

dependency_overrides:
  plugin_platform_interface: ^2.0.0
  shared_preferences: ^2.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: RopaSans
      fonts:
        - asset: assets/fonts/RopaSans.ttf
    - family: LatoRegular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
