name: mwb_connect_app
description: MWBConnect
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.6
  firebase_core: ^0.4.5
  firebase_storage: ^3.1.5
  flutuate_mixpanel: ^1.1.1
  firebase_analytics: ^5.0.2
  flutter_segment: ^2.1.1
  flutter_phoenix: ^0.1.0
  provider: ^4.0.4
  get_it: ^4.0.1
  path_provider: ^1.4.0
  google_fonts: ^1.1.0
  shared_preferences: ^0.5.6+3
  flutter_widget_from_html_core: ^0.4.2
  quiver: ^2.1.3
  smooth_page_indicator: ^0.1.5
  scroll_to_index: ^1.0.6
  flutter_spinkit: ^4.1.2
  uuid: ^2.1.0
  devicelocale: ^0.2.3
  keyboard_visibility: ^0.5.6
  draggable_scrollbar: ^0.0.4
  package_info: ^0.4.1
  flutter_local_notifications: ^1.4.4+2
  rxdart: ^0.23.1
  enum_to_string: ^1.0.9

  flutter_translate:
    path: ./thirdparty/flutter_translate

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: RopaSans
      fonts:
        - asset: assets/fonts/RopaSans.ttf
    - family: LatoRegular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
