name: mwb_connect_app
description: MWBConnect
version: 1.0.0+1

environment:
  sdk: '>=2.9.0 <3.0.0'

publish_to: none  

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.3
  flutter_driver:
    sdk: flutter
  integration_test: ^1.0.2+2
  flutter_localizations:
    sdk: flutter

  firebase_auth: ^1.0.3
  cloud_firestore: ^1.0.4
  cloud_firestore_mocks: ^0.7.0
  firebase_storage: ^8.0.3
  flutuate_mixpanel: ^1.1.8
  firebase_analytics: ^7.1.1
  provider: ^5.0.0
  path_provider: ^2.0.1
  get_it: ^6.0.0
  shared_preferences: ^2.0.5
  flutter_segment: ^3.0.0
  flutter_phoenix: ^1.0.0
  intl: ^0.17.0
  devicelocale: ^0.4.1
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  flutter_native_timezone: ^1.0.10
  flutter_local_notifications: ^5.0.0+1
  flutter_widget_from_html_core: ^0.6.0
  flutter_typeahead: ^3.1.1
  quiver: ^2.1.3
  smooth_page_indicator: ^0.2.3
  scroll_to_index: ^2.0.0
  flutter_spinkit: ^5.0.0
  keyboard_visibility: ^0.5.6
  draggable_scrollbar: ^0.1.0
  package_info: ^2.0.0
  rxdart: ^0.26.0
  enum_to_string: ^2.0.1

  easy_localization:
    git:
      url: git://github.com/MentorsWithoutBorders/easy_localization.git

dependency_overrides:
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: RopaSans
      fonts:
        - asset: assets/fonts/RopaSans.ttf
    - family: LatoRegular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
