name: mwb_connect_app
description: MWBConnect
version: 1.0.0+1

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.1
  flutter_driver:
    sdk: flutter
  integration_test: ^1.0.2+2
  flutter_localizations:
    sdk: flutter

  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  cloud_firestore_mocks: ^0.7.0
  firebase_storage: ^8.0.0
  flutuate_mixpanel: ^1.1.7
  firebase_analytics: ^7.1.1
  provider: ^5.0.0
  path_provider: ^2.0.1
  get_it: ^6.0.0
  shared_preferences: ^2.0.4
  easy_localization: ^3.0.0
  flutter_segment: ^3.0.0
  flutter_phoenix: ^1.0.0
  devicelocale: ^0.4.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  flutter_local_notifications: ^4.0.1+2
  flutter_widget_from_html_core: ^0.5.2+1
  quiver: ^2.1.3
  smooth_page_indicator: ^0.2.1
  scroll_to_index: ^2.0.0
  flutter_spinkit: ^5.0.0
  keyboard_visibility: ^0.5.6
  draggable_scrollbar: ^0.0.4
  package_info: ^2.0.0
  rxdart: ^0.26.0
  enum_to_string: ^1.0.14

dependency_overrides:
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: RopaSans
      fonts:
        - asset: assets/fonts/RopaSans.ttf
    - family: LatoRegular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
