// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBre9YjeRt0nVmeroqVAtJUchCOW7G2G58',
    appId: '1:280651968447:android:bbf6889a22879eb2c4fb0a',
    messagingSenderId: '280651968447',
    projectId: 'mwb-connect',
    databaseURL: 'https://mwb-connect.firebaseio.com',
    storageBucket: 'mwb-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpd8yGV98bkImRcHVwrfN3QKYG0K-Aico',
    appId: '1:280651968447:ios:c512dd3defe17e3ac4fb0a',
    messagingSenderId: '280651968447',
    projectId: 'mwb-connect',
    databaseURL: 'https://mwb-connect.firebaseio.com',
    storageBucket: 'mwb-connect.appspot.com',
    iosClientId: '280651968447-l72heb5f8urqfrjufcjb40v6qa5moe2p.apps.googleusercontent.com',
    iosBundleId: 'com.mwbconnect.app',
  );
}
